### ISSUE TITLE
Run the code with error

### ISSUE THREAD

**Issue by GoingMyWay** [namidairo777/Distributed-MADDPG#2] opened 2019-08-31 11:36 UTC
I run the code with the command you mentioned in the README.md, however, I got the error

```
Traceback (most recent call last):
  File "mpirun_main.py", line 387, in <module>
    main(args)
  File "mpirun_main.py", line 350, in main
    collect_batch(env, args, critics, ave_n)
  File "mpirun_main.py", line 244, in collect_batch
    s_batch, a_batch, target_q = comm.recv(source=0, tag=9)
ValueError: too many values to unpack (expected 3)
```

Could you please check it?

**Comment by namidairo777** [comment] 2019-10-17 03:47
@GoingMyWay 
Hello~ I am sorry for the late response.
Did you follow the same environment as I mentioned in readme?
```
Keras 2.1.2 （tensorflow 1.4 as backend）
mpi4py
Python 3.6
CUDA 8.0 + cuDNN 6.0
```

I don't have these stuff in my local environment, so I cannot reproduce this.
Sorry

**Comment by dcy0324** [comment] 2019-12-24 03:46
Excuse me, how can I see the reward curves of the three algorithms? I do n’t see them when I run the main program.

**Comment by namidairo777** [comment] 2020-01-23 10:00
@dcy0324 It is `tensorboard` which provided by tensorflow
```bash
tensorboard --logdir logs/fit
```

**Comment by qiaopTDUN** [comment] 2020-04-01 17:52
@GoingMyWay , have you handled the problem? I came into the same problem.

**Comment by qiaopTDUN** [comment] 2020-04-01 17:54
@namidairo777 Hi, can you provide the detailed requirements of this projects, such as numpy, gym anything it depends on. Thanks.

**Comment by namidairo777** [comment] 2020-04-13 10:25
@qiaopTDUN Hi~
I am sorry that I have already lost my experiment environment (cause it was the machine in my Lab, I graduated now..)
So currently as I mentioned in readme, some requirements are listed blew
```
Keras 2.1.2 （tensorflow 1.4 as backend）
mpi4py
Python 3.6
CUDA 8.0 + cuDNN 6.0
```
About gym and numpy, I didn't remember though...
Please try to fix any version issue you encounter on your own, I think that also contains some transitive dependencies. 😃

**Comment by GoingMyWay** [comment] 2020-04-14 01:33
> @GoingMyWay , have you handled the problem? I came into the same problem.

Hi, I am not using this library now. Now, I am using Ray[rllib] to run my experiments

**Comment by qiaopTDUN** [comment] 2020-04-18 16:08
> > @GoingMyWay , have you handled the problem? I came into the same problem.
> 
> Hi, I am not using this library now. Now, I am using Ray[rllib] to run my experiments

Hi, I also implemented from scratch now. It fails because receiving or sending data is blocked.

**Comment by qiaopTDUN** [comment] 2020-04-18 16:08
> @qiaopTDUN Hi~
> I am sorry that I have already lost my experiment environment (cause it was the machine in my Lab, I graduated now..)
> So currently as I mentioned in readme, some requirements are listed blew
> 
> ```
> Keras 2.1.2 （tensorflow 1.4 as backend）
> mpi4py
> Python 3.6
> CUDA 8.0 + cuDNN 6.0
> ```
> 
> About gym and numpy, I didn't remember though...
> Please try to fix any version issue you encounter on your own, I think that also contains some transitive dependencies. 😃

Thanks anyway.

**Comment by namidairo777** [comment] 2020-05-01 13:16
I will close this issue 😄

**Closed by namidairo777** 2020-05-01 13:16 UTC
